apiVersion: apps/v1
kind: Deployment
metadata:
  name: favourite-service
  labels:
    app: favourite-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: favourite-service
  template:
    metadata:
      labels:
        app: favourite-service
    spec:
      containers:
      - name: favourite-service
        image: micsvc-ws-aks.azurecr.io/favourite-service-ecommerce-boot:__BUILD_NUMBER__
        ports:
        - containerPort: 8800
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "dev"
        - name: SPRING_ZIPKIN_BASE_URL
          value: "http://zipkin:9411/"
        - name: SPRING_CONFIG_IMPORT
          value: "optional:configserver:http://cloud-config:9296"
        - name: EUREKA_SERVER_URL
          value: "http://service-discovery:8761/eureka/"
        - name: SPRING_APPLICATION_NAME
          value: "FAVOURITE-SERVICE"
        - name: SERVER_PORT
          value: "8800"
        - name: SERVER_SERVLET_CONTEXT_PATH
          value: "/favourite-service"
        # Variables adicionales para base de datos
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:h2:mem:ecommerce_dev_db;DB_CLOSE_ON_EXIT=FALSE"
        - name: SPRING_DATASOURCE_USERNAME
          value: "sa"
        - name: SPRING_DATASOURCE_PASSWORD
          value: ""
        livenessProbe:
          httpGet:
            path: /favourite-service/actuator/health
            port: 8800
          initialDelaySeconds: 90
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /favourite-service/actuator/health
            port: 8800
          initialDelaySeconds: 60
          periodSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: common-config-volume
          mountPath: /app/config
      volumes:
      - name: common-config-volume
        configMap:
          name: common-config 